config/routes.rb
JobProfile::Application.routes.draw do

  resources :jobs

  root :to => 'users#signup'

  get "users/info"
  get "users/new"
  get "users/jobs"
  get "users/notify"

  match 'signup', :to => 'users#signup'
  match 'activate(/:id/:token)' => 'users#activate'
  match '/users/info' => 'users#info'
  match '/users/moreinfo' => 'users#moreinfo'
  match '/logout' => 'users#logout'

  resources :users do
    resources :jobs
  end

end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :user
  
  attr_accessible :title, :company
  
  validates :title, :presence => true, :length => { :maximum => 50 }
  validates :company, :presence => true, :length => { :maximum => 50 }  
  # validates :user_id, :presence => true
end

app/models/user.rb
# == Schema Information
# Schema version: 20110611060437
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  email              :string(255)
#  first_name         :string(255)
#  last_name          :string(255)
#  location           :string(255)
#  birth_date         :date
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  token              :integer
#  active             :boolean
#

require 'digest'

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :first_name, :last_name, :email, :location, :birth_date, :password, :password_confirmation
  has_many :jobs
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :email, :presence => true,
                    :format   => { :with => email_regex },
                    :uniqueness => {:case_sensitive => false}
  validates :first_name, :length   => { :maximum => 50 }
  

  before_save :encrypt_password , :if=>:has_password?
  
  def has_password?
    !@password.blank?
  end

  private
    def encrypt_password
       self.encrypted_password = encrypt(password)
      true
    end

    def encrypt(string)
      Digest::SHA2.hexdigest(string)
    end
  
    def active?
      active
    end
  
    def activate!
      self.active = true
      save
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  # GET /jobs
  # GET /jobs.xml
  def index
    # @jobs = Job.all
    @jobs = Job.find_all_by_user_id(session[:user_id])
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.xml
  def show
    @job = Job.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.xml
  def new
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.xml
  def create
    count = Job.find_all_by_user_id(session[:user_id]).count
    if count >= 7 
      redirect_to ('/jobs', :notice => 'Cannot create more than 7 jobs')
      return
    end
    @job = Job.new(params[:job])
    @job.user_id = session[:user_id]
    respond_to do |format|
      if @job.save
        format.html { redirect_to(@job, :notice => 'Job was successfully created.') }
        format.xml  { render :xml => @job, :status => :created, :location => @job }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @job.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.xml
  def update
    @job = Job.find(params[:id])
    if @job.user_id != session[:user_id]
      redirect_to(@job, :notice => 'Invalid Previledges.') 
    else
      respond_to do |format|
        if @job.update_attributes(params[:job])
          format.html { redirect_to(@job, :notice => 'Job was successfully updated.') }
          format.xml  { head :ok }
        else
          format.html { render :action => "edit" }
          format.xml  { render :xml => @job.errors, :status => :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.xml
  def destroy
    @job = Job.find(params[:id])
    if @job.user_id != session[:user_id]
      redirect_to(@job, :notice => 'Invalid Previledges.') 
    else
      @job.destroy
      respond_to do |format|
        format.html { redirect_to(jobs_url) }
        format.xml  { head :ok }
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def signup
    if request.post?
      @user = User.new(params[:user])
      #Generate a 4 digit random token
      @user.token = 1000 + rand(9000)
      
      if @user.save
        #send email to the user
        UserMailer.welcome_email(@user).deliver
        render 'notify'
      else
        render 'signup'
      end
    else
      #get request
      @user = User.new
    end
  end

  def notify
  end
    
  def activate
    @user = User.find_by_id_and_token(params[:id] , params[:token])
    @user.active = true
    if @user.save
      # request.session_options[:user_id] = @user.id
      session[:user_id] = @user.id
      redirect_to '/users/info'
    else
      render notify
    end
  end

  def info
    @user = User.find_by_id(session[:user_id])
    if request.post?
      @user = @user.update_attributes(params[:user])
      redirect_to '/users/moreinfo'
    end
  end
  
  def moreinfo
    @user = User.find_by_id(session[:user_id])
    if request.post?
      @user = @user.update_attributes(params[:user])
      redirect_to '/jobs'
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_url
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :company %><br />
    <%= f.text_field :company %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<h1>Listing jobs</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Company</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @jobs.each do |job| %>
  <tr>
    <td><%= job.title %></td>
    <td><%= job.company %></td>
    <td><%= link_to 'Show', job %></td>
    <td><%= link_to 'Edit', edit_job_path(job) %></td>
    <td><%= link_to 'Destroy', job, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<p>Number of Jobs : <%= @jobs.count %></p>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @job.title %>
</p>

<p>
  <b>Company:</b>
  <%= @job.company %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobProfile</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="header">
  <ul id="nav">
    <li><a href="/users/info">Info</a></li>
    <li><a href="/users/moreinfo">More info</a></li>
    <li><a href="/jobs">Jobs</a></li>
    <li><a href="/logout">Logout</a></li>    
  </ul>
  
</div>
<%= yield %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> 
        prohibited this user from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/activate.html.erb
<h2>Activation Complete!</h2>

app/views/users/info.html.erb
<h1>User info</h1>

<%= form_for :user do |f| %>
  
  <%= render 'shared/error_messages' %>
  
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  
  <div class="actions">
    <%= f.submit "Continue >" %>
  </div>
<% end %>

app/views/users/jobs.html.erb
<h1>Users#jobs</h1>
<p>Find me in app/views/users/jobs.html.erb</p>

app/views/users/moreinfo.html.erb
<h1>More info</h1>

<%= form_for :user do |f| %>
  
  <%= render 'shared/error_messages' %>
  
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  
  <div class="field">
    <%= f.label :birth_date %><br />
    <%= f.date_select :birth_date %>
  </div>
  
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/users/notify.html.erb
<h1>Email sent, Please confirm </h1>

<h3>Click on the link sent in the email to proceed.</h3>

app/views/users/signup.html.erb
<h1>Sign up</h1>

<%= form_for :user do |f| %>
  
  <%= render 'shared/error_messages' %>
  
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>